Application.Web/Controllers/StockSettingsController.cs
using System.Net.Http;
using System.Threading.Tasks;
using Application.Infrastructure;
using Application.Web.Extensions;
using Application.Web.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Application.Web.Controllers
{
    [Authorize]
    [UserRequest]
    public class StockSettingsController : BaseController
    {
        public StockSettingsController(IConfiguration configuration) : base(configuration)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Stock Settings";
            StockSettings result = null;
            HttpResponseMessage response = await Client.GetAsync($"StockSettings/{User.GetUserId()}");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<StockSettings>();
            }

            return View(result);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(StockSettings model)
        {
            StockSettings result = null;
            HttpResponseMessage response = null;

            response = await Client.PostAsJsonAsync($"StockSettings/{User.GetUserId()}", model);

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<StockSettings>();
                return Redirect("/Stocks");
            }

            return View(model);
        }
    }
}

Application.Web/Controllers/UsersController.cs
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Application.Core.Models;
using Application.Core.Models.ViewModels;
using Application.Infrastructure;
using Application.Web.Extensions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Application.Web.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IConfiguration _configuration;

        public UsersController(IConfiguration configuration) : base(configuration)
        {
        }


        // GET


        [HttpGet]
        public IActionResult Index()
        {
            return View(new LoginRegisterViewModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> _LoginPartial(LoginViewModel model)
        {
            ViewBag.Title = "Login";
            if (ModelState.IsValid)
            {
                Users user = null;

                HttpResponseMessage response = await Client.PostAsJsonAsync("Users/Login", model);


                if (response.IsSuccessStatusCode)
                {
                    user = await response.Content.ReadAsAsync<Users>();

                    if (user != null)
                    {
                        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                        identity.AddClaim(new Claim("UserId", user.Id));
                        identity.AddClaim(new Claim("UserName", user.UserName));
                        identity.AddClaim(new Claim("Password", user.Password));
                        identity.AddClaim(new Claim("Token", user.Token));
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(identity));

                        HttpContext.Session.SetObjectAsJson("Token", user.Token);

                        return Redirect("/Stocks");
                    }
                }

                // ViewBag.Message = result?.ReturnMessage;
            }

            return View("Index", new LoginRegisterViewModel() {loginViewModel = model});
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> _RegisterPartial(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                Result result = null;


                HttpResponseMessage response = await Client.PostAsJsonAsync("/Users/Register", model);
                response.EnsureSuccessStatusCode();
                if (response.IsSuccessStatusCode)
                {
                    result = await response.Content.ReadAsAsync<Result>();
                }

                if (result.IsSuccess)
                {
                    //      Current.User = new userSessionModel()
                    //        { userGUID = result.ReturnMessageList[0], userName = result.ReturnMessageList[1] };

                    return Redirect("/Stock/Index");
                }

                ViewBag.Message = result.ReturnMessage;
            }

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Response.Cookies.Delete("Token");
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction("Index");
        }
    }
}

Application.Web/Views/Shared/_Layout.cshtml
@using System.Net.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Application.Web</title>

        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>

   
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@if (!string.IsNullOrEmpty(Current.User.userGUID))
            {
                <b class="navbar-brand">Welcome @Current.User.userName</b>
            }
            else
            {
                @Html.ActionLink("Stocks", "Index", "Stock", new { area = "" }, new { @class = "navbar-brand" })
            }*@
    
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {

                    <li>@Html.ActionLink("Add Stock", "StockForm", "Stocks")</li>
                    <li>@Html.ActionLink("Stock List", "Index", "Stocks")</li>
                    <li>@Html.ActionLink("Stock Settings", "Index", "StockSettings")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Users")</li>
                }
                else
                { 
                    <li>@Html.ActionLink("Login", "Index", "Users")</li>
                } 
            </ul>
              
        </div>
    </div>
</div>
<div class="container body-content">
    <div class="panel">
        <h1>@ViewBag.Title</h1>
    </div>

    
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Osman Kadir KARTAL</p>
    </footer>
</div>


    @RenderSection("Scripts", required: false)
</body>
</html>