Application.Web/Controllers/StocksController.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Application.Core.Models;
using Application.Infrastructure;
using Application.Web.Extensions;
using Application.Web.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Application.Web.Controllers
{
    [Authorize]
    [UserRequest]
    public class StocksController : BaseController
    {
        public StocksController(IConfiguration configuration) : base(configuration)
        {
        }


        private async Task<int> GetStockSettings()
        {
            StockSettings result = null;

            HttpResponseMessage response = await Client.GetAsync($"StockSettings/{User.GetUserId()}/");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<StockSettings>();
                return result.TickerSecond;
            }

            return 0;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Stock List";
            IEnumerable<Stocks> result = null;

            HttpResponseMessage response = await Client.GetAsync($"Stock/StockList/{User.GetUserId()}");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<IEnumerable<Stocks>>();
            }

            TempData["TickerSecond"] = await GetStockSettings();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> StockForm(string stockId)
        {
            ViewBag.Title = "Stock Form";
            Stocks result = null;

            HttpResponseMessage response = await Client.GetAsync($"Stock/Stock/{stockId}/{User.GetUserId()}");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<Stocks>();
            }

            return View(result);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> StockForm(Stocks stock)
        {
            Stocks result = null;
            HttpResponseMessage response = null;

            stock.UserId = User.GetUserId();

            if (stock.Id == null)
            {
                response = await Client.PostAsJsonAsync("Stock/AddStock/", stock);
            }
            else
            {
                response = await Client.PutAsJsonAsync($"Stock/{stock.Id}", stock);
            }

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View(stock);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteStock(string stockId)
        {
            ViewBag.Title = "Delete Stock";

            Stocks result = null;

            HttpResponseMessage response = await Client.GetAsync($"Stock/Stock/{stockId}/{User.GetUserId()}");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<Stocks>();
            }

            return View(result);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteStock(Stocks stock)
        {
            ViewBag.Title = "Delete Stock";
            Result result = null;

            HttpResponseMessage response =
                await Client.DeleteAsync($"Stock?stockId={stock.Id}&userId={User.GetUserId()}");

            if (response.IsSuccessStatusCode)
            {
                result = await response.Content.ReadAsAsync<Result>();
                return RedirectToAction("Index");
            }

            return View(stock);
        }
    }
}

Application.Web/Views/Stocks/DeleteStock.cshtml
@using Application.Infrastructure
@model Stocks

<form id="formDelete" method="post" action="DeleteStock"
      enctype="application/x-www-form-urlencoded">
    @Html.HiddenFor(x => x.UserId)
    @Html.HiddenFor(x => x.Id)
    <div>
        <label>@Html.DisplayNameFor(x => x.Id)</label>
          @Model.Id
    </div>
    <div>
        <label>@Html.DisplayNameFor(x => x.Code)</label>
        @Model.Code
    </div>
    <div>
        <label>@Html.DisplayNameFor(x => x.Name)</label>
        @Model.Name
    </div>
    <div>
        <label>@Html.DisplayNameFor(x => x.Price)</label>
        @Model.Price
    </div>
    <div>
        Are you sure delete this stock?
        <input type="submit" value="Delete"/>
        <a href="/Stocks">Return List</a>
    </div>
</form>

Application.Web/Views/Stocks/Index.cshtml
@using Application.Infrastructure
@model IEnumerable<Stocks>

 
@if ( TempData["TickerSecond"] != "0")
{
    <script type="text/javascript">setTimeout(function () { location.reload(1); }, @TempData["TickerSecond"]);</script>
}

@if (Model.Any())
{
    <table class="table table-striped table-bordered table-responsive table-condensed table-hover">
        <tr>
            <th>@Html.DisplayNameFor(x=>x.Id)</th>
            <th>@Html.DisplayNameFor(x=>x.Code)</th>
            <th>@Html.DisplayNameFor(x=>x.Name)</th>
            <th>@Html.DisplayNameFor(x=>x.Price)</th>
            <th>@Html.DisplayNameFor(x=>x.Piece)</th>
            <th>@Html.DisplayNameFor(x=>x.IsActive) ?</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
          
        @foreach (Stocks stock in Model)
        {
    
                 <tr>
                     <td>@stock.Id </td>
                     <td>@stock.Code</td>
                     <td>@stock.Name</td>
                     <td>@stock.Price </td> 
                     <th>@stock.Piece</th>
                     <td>@(stock.IsActive) </td> 
                     <td>@Html.ActionLink("Edit","StockForm","Stocks",new {stockId=@stock.Id,userId=@stock.UserId})</td>
                     <td><a href="/Stocks/DeleteStock/@stock.UserId/@stock.Id">[Delete]</a></td>
                 </tr>
           
        }


    </table>
}
else
{
    <div>There is  no stocks</div>
}

Application.Web/Views/Stocks/StockForm.cshtml
@using Application.Infrastructure
@model Stocks 

<form id="stockEditForm" method="post"  asp-action="StockForm" asp-controller="Stocks">
    @Html.HiddenFor(x=>x.UserId)
    @Html.HiddenFor(x=>x.Id)
     
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    <table class="table table-striped table-bordered table-responsive table-condensed table-hover">
        <tr>
            <td>@Html.DisplayNameFor(x=>x.Code)</td>
            <td>@Html.TextBoxFor(model => model.Code, new {maxlength = 10})</td>
         </tr>
        
        <tr>
            <td>@Html.DisplayNameFor(x=>x.Name)</td>
            <td>@Html.TextBoxFor(model => model.Name, new {maxlength = 20})</td>
         </tr>
        
        <tr>
            <td>@Html.DisplayNameFor(x=>x.Price)</td>
            <td>@Html.TextBoxFor(model => model.Price, new {maxlength = 10})</td>
         </tr>
        
        
        <tr>
            <td>@Html.DisplayNameFor(x=>x.Piece)</td>
            <td>@Html.TextBoxFor(model => model.Piece, new {maxlength = 10})</td>
         </tr>
        
        <tr>
            <td>@Html.DisplayNameFor(x=>x.IsActive)?</td>
            <td>Yes @Html.RadioButtonFor(model => model.IsActive, "1")
                No @Html.RadioButtonFor(model => model.IsActive, "0")</td>
         </tr>
        <tr>
            <td colspan="3" align="center">
                <button class="btn btn-inverse" type="submit">Save</button>
            </td>
        </tr>
       
</table>
    
   
   
</form>